### call logic app

POST https://prod-176.westeurope.logic.azure.com:443/workflows/0568b038e8d34d68bde416bb17efcd03/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=jdnMpUreBTpIp9xtWbv1m092GomUI074u_-WXDzNHEc
Content-Type: application/json

{
    "productId": "75542e38-563f-436f-adeb-f426f1dabb5c"
}

### Create Request
POST http://localhost:7071/api/CreateRating
Content-Type: application/json

{
  "id": "79c2779e-dd2e-43e8-803d-ecbebed8972c",
  "userId": "cc20a6fb-a91f-4192-874d-132493685376",
  "productId": "4c25613a-a3c2-4ef3-8e02-9c335eb23204",
  "timestamp": "2018-05-21 21:27:47Z",
  "locationName": "Sample ice cream shop",
  "rating": 5,
  "userNotes": "I love the subtle notes of orange in this ice cream!"
}

### Get Ratings by rating (rating and partition key)
GET http://localhost:7071/api/GetRating?ratingId=5&partitionKeyValue=1e51f6d9-3ea7-46ea-8d9f-acc0c2b2a9ea
Content-Type: application/json

### Get Ratings by user
GET http://localhost:7071/api/GetRatings?userid=cc20a6fb-a91f-4192-874d-132493685376
Content-Type: application/json

### Get Ratings by user - path routing - needs   "route": "GetRatings/{userid}",
GET http://localhost:7071/api/GetRatings/cc20a6fb-a91f-4192-874d-132493685376
Content-Type: application/json


### DEPENDENCIES call get product
GET https://serverlessohproduct.trafficmanager.net/api/GetProduct?productid=4c25613a-a3c2-4ef3-8e02-9c335eb23204
Content-Type: application/json



### call get user
GET https://serverlessohuser.trafficmanager.net/api/GetUser?userid=cc20a6fb-a91f-4192-874d-132493685376
Content-Type: application/json
